
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class fees extends javax.swing.JFrame {
    String b;
    int d=0;

    /**
     * Creates new form fees
     */
    public fees() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cfee = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cpaid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cdate = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jc1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tr = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cfee.setEditable(false);
        getContentPane().add(cfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 466, 249, -1));

        jLabel5.setText("Course Fee");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 469, 100, -1));

        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 610, 100, -1));

        cpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpaidActionPerformed(evt);
            }
        });
        cpaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpaidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpaidKeyTyped(evt);
            }
        });
        getContentPane().add(cpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 518, 250, -1));

        jButton1.setText("Paid Fee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, 141, 57));

        jLabel1.setText("Student id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 332, 100, -1));

        jLabel2.setText("Course name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 417, 100, -1));

        cdate.setEnabled(false);
        getContentPane().add(cdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 610, 250, -1));

        jLabel4.setText("Fees paid");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 520, 100, -1));

        cname.setEditable(false);
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 414, 249, -1));

        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 329, 250, -1));

        jLabel6.setText("Student name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 369, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 374, 250, -1));

        jLabel7.setText("Balance");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 564, -1, -1));

        bal.setEditable(false);
        bal.setBackground(new java.awt.Color(204, 204, 204));
        bal.setForeground(new java.awt.Color(102, 102, 102));
        bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balActionPerformed(evt);
            }
        });
        getContentPane().add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 564, 250, -1));

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 141, 55));

        tr.setColumns(20);
        tr.setRows(5);
        jScrollPane1.setViewportView(tr);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 329, 465, 303));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, 142, 55));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feeLogo.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 302, 281));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeeBAckground.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void getFee()
{
     try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/institute","root","1761");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from course where course_name='"+cname.getText()+"'");
            if(rs.next())
            {
              cfee.setText(String.valueOf(rs.getInt(3)));
              d=rs.getInt(3);
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }  
}
     public void fillCombo()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/institute","root","1761");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from student");
            while(rs.next())
            {
                jc1.addItem(String.valueOf(rs.getInt(1)));
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }  
    }
    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
         try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/institute","root","1761");
            Statement stmt,stmt2,stmt3 = null,stmt4 = null;
            stmt=conn.createStatement();
                        stmt2=conn.createStatement();

            ResultSet rs=stmt.executeQuery("select * from student where studid='"+jc1.getSelectedItem()+"'");
            ResultSet rs8=stmt2.executeQuery("select balance from fees where studid='"+jc1.getSelectedItem()+"'");
            
            if(rs.next())
            {
                name.setText((rs.getString(2)));
                cname.setText(rs.getString(8));
                
            }
            if(rs8.next())
            {
                bal.setText(String.valueOf(rs8.getInt("balance")));
            }
            else
            {
                bal.setText("0");
            }
             
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    } 
         getFee();
    }//GEN-LAST:event_jc1ActionPerformed

    private void balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{

    int b=0,t=0,k=0;
    Class.forName("com.mysql.jdbc.Driver");
    
    PreparedStatement stmt1;
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/institute","root","1761");
    Statement stmt,stmt3,stmt4,stmt5;
            stmt3=conn.createStatement();
            stmt4=conn.createStatement();
            stmt5=conn.createStatement();
            ResultSet rs0=stmt3.executeQuery("select studid from fees where studid='"+jc1.getSelectedItem()+"'");
            ResultSet rs1=stmt4.executeQuery("select studid from student where studid='"+jc1.getSelectedItem()+"'");
            ResultSet rs2=stmt5.executeQuery("select * from fees where studid='"+jc1.getSelectedItem()+"'");
            
            if(rs2.next())
            {
           b=rs2.getInt(5);
           t=rs2.getInt(2);
           
            }
          k= (Integer.parseInt(cpaid.getText()));
   if(rs0.next()==rs1.next())
   {
       if(b==0 || (Integer.parseInt(cpaid.getText())>b) || (Integer.parseInt(cpaid.getText())) >d )
       {
           JOptionPane.showMessageDialog(null,"Fees Are already paid/fees are greater than balance/Amount is graeter than course fee");
           tr.removeAll();
       }
       
       else{
           bal.setText(String.valueOf(b));
      stmt1=conn.prepareStatement("update fees set studid=?,amount=?,date=?,course_name=?,balance=?,sname=? where studid='"+jc1.getSelectedItem()+"'");
       
 					stmt1.setInt(1,(Integer.parseInt(jc1.getSelectedItem().toString())));
                                        t=t+(Integer.parseInt(cpaid.getText()));
                                         stmt1.setInt(2,t);
                                        stmt1.setString(3,cdate.getText());
					stmt1.setString(4,cname.getText());
                                        int x,y,z;
                                         x=b;
                                        y=Integer.parseInt(cpaid.getText());
                                        z=x-y;
                                        bal.setText(String.valueOf(z));
					stmt1.setInt(5,(Integer.parseInt(bal.getText())));
					stmt1.setString(6,name.getText());
					stmt1.executeUpdate();	
					JOptionPane.showMessageDialog(null, "Fees Paid");
					stmt1.close();
                                         tr.append("\t FEE Receipt \n\n"+
                   
        "\n=========================================================\n"+
        "\tStudent ID   =    "+jc1.getSelectedItem()+"\n\n"+
        "\tStudent Name =    "+name.getText()+"\n\n"+
        "\tCourse Name  =    "+cname.getText()+"\n\n"+
        "\tCourse Fee   =    "+cfee.getText()+"\n\n"+
        "\tAmount Paid  =    "+cpaid.getText()+"\n\n"+
        "\tBalance      =    "+bal.getText()+"\n\n" );
      
   name.setText("");
   cpaid.setText("");
   cname.setText("");
   cfee.setText("");
bal.setText("");
       }
   }
   
   else
   {
       if((Integer.parseInt(cpaid.getText())) >d)
       {
         JOptionPane.showMessageDialog(null, "Fees are greater than course fee");  
       }
       else{
       stmt1=conn.prepareStatement("insert into fees values(?,?,?,?,?,?)");
     
 					stmt1.setInt(1,(Integer.parseInt(jc1.getSelectedItem().toString())));
                                        stmt1.setInt(2,(Integer.parseInt(cpaid.getText())));
                                        stmt1.setString(3,cdate.getText());
					stmt1.setString(4,cname.getText());
                                         int x,y,z;
                                         x=Integer.parseInt(cfee.getText());
                                        y=Integer.parseInt(cpaid.getText());
                                        z=x-y;
        bal.setText(String.valueOf(z));
					stmt1.setInt(5,(Integer.parseInt(bal.getText())));
					stmt1.setString(6,name.getText());
					stmt1.executeUpdate();	
					JOptionPane.showMessageDialog(null, "Fees Paid");
					stmt1.close();
                                         tr.append("\t FEE Receipt \n\n"+
                   
        "\n=========================================================\n"+
        "\tStudent ID   =    "+jc1.getSelectedItem()+"\n\n"+
        "\tStudent Name =    "+name.getText()+"\n\n"+
        "\tCourse Name  =    "+cname.getText()+"\n\n"+
        "\tCourse Fee   =    "+cfee.getText()+"\n\n"+
        "\tAmount Paid  =    "+cpaid.getText()+"\n\n"+
        "\tBalance      =    "+bal.getText()+"\n\n" );
      
   name.setText("");
   cpaid.setText("");
   cname.setText("");
   cfee.setText("");
bal.setText("");
       }
       }   
      
}

catch(Exception e)
{
   JOptionPane.showMessageDialog(null, e.getMessage());
    }                                                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cpaidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpaidKeyTyped

    }//GEN-LAST:event_cpaidKeyTyped

    private void cpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpaidActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_cpaidActionPerformed

    private void cpaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpaidKeyReleased
       
               // TODO add your handling code here:
         
            
            
    
    }//GEN-LAST:event_cpaidKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
home h=new home();
h.setSize(h.getSize());
h.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            tr.print();
        } catch (PrinterException ex) {
            Logger.getLogger(fees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bal;
    private datechooser.beans.DateChooserCombo cdate;
    private javax.swing.JTextField cfee;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cpaid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> jc1;
    private javax.swing.JTextField name;
    private javax.swing.JTextArea tr;
    // End of variables declaration//GEN-END:variables
}
