/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.*;
public class Student extends javax.swing.JFrame {
static int inc;
boolean ins=false;
String fn=null;
File f;
byte[] stud_image=null;
    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sname = new javax.swing.JTextField();
        sq = new javax.swing.JTextField();
        smno = new javax.swing.JTextField();
        scourse = new javax.swing.JComboBox<>();
        sadmission = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        saddress = new javax.swing.JTextArea();
        sgender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sdob = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentbackground.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 153, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel2.setText("DOB");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 41, -1));

        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabel5.setText("Qualification");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel6.setText("Mobileno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel7.setText("Course Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel8.setText("Admission date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 80, 30));
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 272, -1));
        getContentPane().add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 272, -1));
        getContentPane().add(smno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 271, -1));

        scourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select course" }));
        getContentPane().add(scourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 271, -1));
        getContentPane().add(sadmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 271, -1));

        saddress.setColumns(20);
        saddress.setRows(5);
        jScrollPane1.setViewportView(saddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 271, -1));
        getContentPane().add(sgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 272, -1));

        jLabel9.setText("Student Id");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 272, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 100, 30));

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 100, 30));

        lbl_img.setText("Photo");
        lbl_img.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 188, 183));

        jButton4.setText("Load");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        jLabel10.setText("Learner ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        lid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lidActionPerformed(evt);
            }
        });
        getContentPane().add(lid, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 230, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentregistrationlogo.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 560, 150));
        getContentPane().add(sdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 297, 272, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentbackground.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void fillCombo()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/institute","root","1761");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from course");
            while(rs.next())
            {
                scourse.addItem(rs.getString(2));
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }  
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(ins==true)
    {
        try
{
    Class.forName("com.mysql.jdbc.Driver");
    
    
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/institute","root","1761");
    PreparedStatement stmt1;
    File f1=new File(f.getAbsolutePath());
    FileInputStream fis=new FileInputStream(f1);
    
    
    stmt1=conn.prepareStatement("insert into student  values(?,?,?,?,?,?,?,?,?,?,?)");
					stmt1.setInt(1,(Integer.parseInt(sid.getText())));
					stmt1.setString(2,sname.getText());
					stmt1.setString(3,sdob.getText());
                                        stmt1.setString(4,sadmission.getText());
					stmt1.setString(5,saddress.getText());
                                        stmt1.setString(6,smno.getText());
                                        stmt1.setString(7,sgender.getText());
                                        stmt1.setString(8,scourse.getSelectedItem().toString());
                                        stmt1.setString(9,sq.getText());
                                        stmt1.setBinaryStream(10, fis);
                                        stmt1.setInt(11,(Integer.parseInt(lid.getText())));
					stmt1.executeUpdate();	
					JOptionPane.showMessageDialog(null, "Inserted");
					stmt1.close();
                                    
}
catch(Exception e)
{
   JOptionPane.showMessageDialog(null, e.getMessage());
    }
// TODO add your handling code here:
    }
    else
        JOptionPane.showMessageDialog(null,"Please click on Add Button");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/institute","root","1761");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from student");
            while(rs.next())
            {
                inc=rs.getInt(1);
            }
           
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
           inc++;
            sid.setText(String.valueOf(inc));
            sid.setEditable(false);
            sname.setText("");
            sdob.setText("");
            sgender.setText("");
            smno.setText("");
            saddress.setText("");
            sq.setText("");
            sadmission.setText("");
            lid.setText("");
            //scourse.removeAll();
            
                 ins=true;   
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
home h=new home();
h.setSize(h.getSize());
h.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
         f=chooser.getSelectedFile();
        fn=f.getAbsolutePath();
        ImageIcon img=new ImageIcon(new ImageIcon(fn).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
        lbl_img.setIcon(img);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void lidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField lid;
    private javax.swing.JTextArea saddress;
    private datechooser.beans.DateChooserCombo sadmission;
    private javax.swing.JComboBox<String> scourse;
    private javax.swing.JTextField sdob;
    private javax.swing.JTextField sgender;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField smno;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField sq;
    // End of variables declaration//GEN-END:variables
}
